'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";
import { Provider } from 'react-redux';
import { QueryClient, QueryClientProvider } from 'react-query';
// import { store } from '../redux/store';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body >
        {/* <Provider store={store}> */}
        <QueryClientProvider client={queryClient}>
        {children}
        </QueryClientProvider>
         
        {/* </Provider> */}
      </body>
    </html>
  );
}



